apiVersion: cpi.tanzu.vmware.com/v1alpha1
kind: VSphereCPIConfig
metadata:
  name: vspherecpiconfig-sample
spec:
  vsphereCPI:
    mode: vsphereCPI
    tlsThumbprint: "test"
    server: 10.1.1.1
    datacenter: ds-test
    vSphereCredentialLocalObjRef:
      apiGroup: ""
      kind: Secret
      name: vsphere-credentials
    insecureFlag: False
    vmInternalNetwork: null
    vmExternalNetwork: null
    cloudProviderExtraArgs:
      tlsCipherSuites: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    nsxt:
      podRoutingEnabled: false
      routes:
        routerPath: ""
      credentialLocalObjRef:
        apiGroup: ""
        kind: Secret
        name: nsxt-credentials
      host: "10.1.1.2"
      insecureFlag: false
      remoteAuth: false
      vmcAccessToken: ""
      vmcAuthHost: ""
      clientCertKeyData: ""
      clientCertData: ""
      rootCAData: ""
      secretName: "cloud-provider-vsphere-nsxt-credentials"
      secretNamespace: "kube-system"
