apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ytt/vendir/vsphere_cpi/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: 0fa3055c5cddf67f8c23edea420575cb4eb7d5d8
    includePaths:
    - addons/packages/vsphere-cpi/1.22.5/bundle/config/**/*
- path: ytt/vendir/cni/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/tce.git
      ref: daa90ee40f373474c7714e72182b7ad784c2ffaf
    includePaths:
    - addons/packages/antrea/1.2.3/bundle/config/**/*
    - addons/packages/calico/3.19.1/bundle/config/**/*
- path: ytt/vendir/kapp-controller/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: f74f471e03ed2d026fbf8083c245b01f659602e8
    includePaths:
    - addons/packages/kapp-controller/0.34.0/bundle/config/**/*
